#=============================================================================
# dark_powered.toml --- dark powered configuration example for SpaceVim
# Copyright (c) 2016-2017 Wang Shidong & Contributors
# Author: Wang Shidong < wsdjeg at 163.com >
# URL: https://spacevim.org
# License: GPLv3
#=============================================================================

# All SpaceVim option below [option] section
[options]
    # set spacevim theme. by default colorscheme layer is not loaded,
    # if you want to use more colorscheme, please load the colorscheme
    # layer
    #colorscheme = "CosmicLatte"
    colorscheme = "hybrid"
    # colorscheme = "gruvbox"
    #colorscheme_bg = "dark"
    background = "dark"
    # Disable guicolors in basic mode, many terminal do not support 24bit
    # true colors
    enable_guicolors = true
    # Disable statusline separator, if you want to use other value, please
    # install nerd fonts
    statusline_separator = "arrow"
    statusline_inactive_separator = "arrow"
    buffer_index_type = 4
    enable_tabline_filetype_icon = true
    enable_statusline_display_mode = false
    filemanager = "nerdtree"

# Enable autocomplete layer
[[layers]]
name = "autocomplete"
auto-completion-return-key-behavior = "complete"
auto-completion-tab-key-behavior = "smart"

[[layers]]
name = "shell"
default_position = "top"
default_height = 30

[[layers]]
name = "unite"

[[layers]]
  name = "lang#typescript"

[[layers]]
  name = "lang#haskell"

[[layers]]
name = "lang#javascript"

[[layers]]
name = "ui"

[[layers]]
name = "tools#dash"

[[layers]]
name = "tumx"

[[layers]]
  name = "lang#python"
  format-on-save = 1

[[layers]]
  name = "lang#purescript"
  
[[layers]]
  name = "lang#markdown"

[[layers]]
  name = "lsp"
  filetypes = [
    "haskell",
    "sh",
    "purescript"
  ]
  [layers.override_cmd]
    haskell = ['hie-wrapper']
    purescript = ['purescript-language-server', '--stdio']
    sh = ['bash-language-server', 'start']

[[layers]]
name = "floobits"

[[layers]]
  name = "checkers"

[[layers]]
  name = "colorscheme"

[[custom_plugins]]
  name = "nightsense/cosmic_latte"
  merged = 0
